# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Neighborhood.create!(name: "Near North Side")
Neighborhood.create!(name: "Loop")
Neighborhood.create!(name: "South Loop")
Neighborhood.create!(name: "North Center")
Neighborhood.create!(name: "Lakeview")
Neighborhood.create!(name: "Lincoln Park")
Neighborhood.create!(name: "Avondale")
Neighborhood.create!(name: "Logan Square")
Neighborhood.create!(name: "Rogers Park")
Neighborhood.create!(name: "West Ridge")
Neighborhood.create!(name: "Uptown")
Neighborhood.create!(name: "Lincoln Square")
Neighborhood.create!(name: "Edison Park")
Neighborhood.create!(name: "Norwood Park")
Neighborhood.create!(name: "Jefferson Park")
Neighborhood.create!(name: "Forest Glen")
Neighborhood.create!(name: "North Park")
Neighborhood.create!(name: "Albany Park")
Neighborhood.create!(name: "O'Hare")
Neighborhood.create!(name: "Edgewater")
Neighborhood.create!(name: "Portage Park")
Neighborhood.create!(name: "Irving Park")
Neighborhood.create!(name: "Dunning")
Neighborhood.create!(name: "Montclare")
Neighborhood.create!(name: "Belmont Cragin")
Neighborhood.create!(name: "Hermosa")
Neighborhood.create!(name: "Humboldt Park")
Neighborhood.create!(name: "West Town")
Neighborhood.create!(name: "Austin")
Neighborhood.create!(name: "West Garfield Park")
Neighborhood.create!(name: "East Garfield Park")
Neighborhood.create!(name: "Near West Side")
Neighborhood.create!(name: "North Lawndale")
Neighborhood.create!(name: "South Lawndale")
Neighborhood.create!(name: "Pilsen")
Neighborhood.create!(name: "Armour Square")
Neighborhood.create!(name: "Douglas")
Neighborhood.create!(name: "Oakland")
Neighborhood.create!(name: "Fuller Park")
Neighborhood.create!(name: "Grand Boulevard")
Neighborhood.create!(name: "Kenwood")
Neighborhood.create!(name: "Washington Park")
Neighborhood.create!(name: "Hyde Park")
Neighborhood.create!(name: "Woodlawn")
Neighborhood.create!(name: "South Shore")
Neighborhood.create!(name: "Bridgeport")
Neighborhood.create!(name: "Greater Grand Crossing")
Neighborhood.create!(name: "Garfield Ridge")
Neighborhood.create!(name: "Archer Heights")
Neighborhood.create!(name: "Brighton Park")
Neighborhood.create!(name: "McKinley Park")
Neighborhood.create!(name: "New City")
Neighborhood.create!(name: "West Elsdon")
Neighborhood.create!(name: "Gage Park")
Neighborhood.create!(name: "Clearing")
Neighborhood.create!(name: "West Lawn")
Neighborhood.create!(name: "Chicago Lawn")
Neighborhood.create!(name: "West Englewood")
Neighborhood.create!(name: "Englewood")
Neighborhood.create!(name: "Chatham")
Neighborhood.create!(name: "Avalon Park")
Neighborhood.create!(name: "South Chicago")
Neighborhood.create!(name: "Burnside")
Neighborhood.create!(name: "Calumet Heights")
Neighborhood.create!(name: "Roseland")
Neighborhood.create!(name: "Pullman")
Neighborhood.create!(name: "South Deering")
Neighborhood.create!(name: "East Side")
Neighborhood.create!(name: "West Pullman")
Neighborhood.create!(name: "Riverdale")
Neighborhood.create!(name: "Hegewisch")
Neighborhood.create!(name: "Ashburn")
Neighborhood.create!(name: "Auburn Gresham")
Neighborhood.create!(name: "Beverly")
Neighborhood.create!(name: "Washington Heights")
Neighborhood.create!(name: "Mount Greenwood")
Neighborhood.create!(name: "Morgan Park")


User.create!(user_name: "mike.browne", email: "mike@email.com", password: "password", neighborhood_id: 1)
User.create!(user_name: "peter.jang", email: "peter@email.com", password: "password", neighborhood_id: 1)
User.create!(user_name: "john.smith", email: "john@email.com", password: "password", neighborhood_id: 1)
User.create!(user_name: "kelly.johnson", email: "kelly@email.com", password: "password", neighborhood_id: 1)
User.create!(user_name: "elizabeth.toews", email: "elizabeth@email.com", password: "password", neighborhood_id: 1)
User.create!(user_name: "daron.collins", email: "daron@email.com", password: "password", neighborhood_id: 1)
User.create!(user_name: "emmit.kane", email: "emmit@email.com", password: "password", neighborhood_id: 1)
User.create!(user_name: "james.thompson", email: "james@email.com", password: "password", neighborhood_id: 8)
User.create!(user_name: "jessica.flowers", email: "jessica@email.com", password: "password", neighborhood_id: 8)
User.create!(user_name: "dylan.styles", email: "dylan@email.com", password: "password", neighborhood_id: 8)
User.create!(user_name: "josh.conway", email: "josh@email.com", password: "password", neighborhood_id: 8)
User.create!(user_name: "sheila.kasova", email: "sheila@email.com", password: "password", neighborhood_id: 9)
User.create!(user_name: "leah.boblick", email: "leah@email.com", password: "password", neighborhood_id: 3)

Attraction.create!(name: "Wiener Circle", address: "2622 N Clark St, Chicago, IL", neighborhood_id: 6)
Attraction.create!(name: "McDonalds", address: "600 N Clark St, Chicago, IL", neighborhood_id: 1)
Attraction.create!(name: "Small Cheval", address: "1732 N Milwaukee Ave, Chicago, IL", neighborhood_id: 28)
Attraction.create!(name: "Uncle Remus Chicken", address: "5611 W Madison St, Chicago, IL", neighborhood_id: 29)
Attraction.create!(name: "Kuma's Corner", address: "2900 W Belmont Ave, Chicago, IL", neighborhood_id: 7)
Attraction.create!(name: "Palmisano Park", address: "2700 S Halsted St, Chicago, IL", neighborhood_id: 46)
Attraction.create!(name: "Afghan Kabob", address: "4040 W Montrose Ave, Chicago, IL", neighborhood_id: 18)
Attraction.create!(name: "Cambodian American Heritage Museum", address: "2831 W Lawrence Ave, Chicago, IL", neighborhood_id: 18)
Attraction.create!(name: "Illinois Bar & Grill", address: "4135 W 47th St, Chicago, IL", neighborhood_id: 49)
Attraction.create!(name: "Chinese American Museum of Chicago", address: "238 W 23rd St, Chicago, IL", neighborhood_id: 36)
Attraction.create!(name: "Bogan Park", address: "3939 W 79th St, Chicago, IL", neighborhood_id: 72)
Attraction.create!(name: "Jamison's Soul Food", address: "1800 W. 87th St, Chicago, IL", neighborhood_id: 73)
Attraction.create!(name: "Avalon Park", address: "1215 E 83rd St, Chicago, IL", neighborhood_id: 61)
Attraction.create!(name: "Millennium Park", address: "201 E Randolph St, Chicago, IL", neighborhood_id: 2)
Attraction.create!(name: "Field Museum", address: "1400 S Lake Shore Dr, Chicago, IL", neighborhood_id: 3)
Attraction.create!(name: "Soldier Field", address: "1410 Museum Campus Dr, Chicago, IL ", neighborhood_id: 3)
Attraction.create!(name: "Half Acre Brewery", address: "4257 N Lincoln Ave, Chicago, IL", neighborhood_id: 4)
Attraction.create!(name: "Wrigley Field", address: "1060 W Addison St, Chicago, IL", neighborhood_id: 5)
Attraction.create!(name: "Loyola Beach", address: "1230 W Greenleaf Ave, Chicago, IL", neighborhood_id: 9)
Attraction.create!(name: "Ghareeb Nawaz Restaurant", address: "2032 W Devon Ave, Chicago, IL", neighborhood_id: 10)
Attraction.create!(name: "My Buddy's Bar", address: "4416 N Clark St, Chicago, IL", neighborhood_id: 11)
Attraction.create!(name: "Garcia's Restaurant", address: "4760 N Lincoln Ave, Chicago, IL", neighborhood_id: 12)
Attraction.create!(name: "Firewater Saloon", address: "6689 N Oliphant Ave, Chicago, IL", neighborhood_id: 13)
Attraction.create!(name: "Superdawg Drive-In", address: "6363 N Milwaukee Ave, Chicago, IL", neighborhood_id: 14)
Attraction.create!(name: "Copernicus Center", address: "5216 W Lawrence Ave, Chicago, IL 60630", neighborhood_id: 15)
Attraction.create!(name: "Edgebrook Golf Course", address: "6100 N Central Ave, Chicago, IL", neighborhood_id: 16)
Attraction.create!(name: "Northeastern Illinois University", address: "5500 N St Louis Ave, Chicago, IL 60625", neighborhood_id: 17)
Attraction.create!(name: "Chicago O'Hare International Airport", address: "10000 W O'Hare Ave, Chicago, IL", neighborhood_id: 19)
Attraction.create!(name: "Ethiopian Diamond", address: "6120 N Broadway, Chicago, IL", neighborhood_id: 20)
Attraction.create!(name: "Montrose Deli", address: "5411 W Montrose Ave, Chicago, IL", neighborhood_id: 21)
Attraction.create!(name: "Smoque BBQ", address: "3800 N Pulaski Rd, Chicago, IL", neighborhood_id: 22)
Attraction.create!(name: "Hubble Hookah", address: "3308 Harlem Ave, Chicago, IL", neighborhood_id: 23)
Attraction.create!(name: "Reuter's Bakery", address: "7177 W Grand Ave, Chicago, IL", neighborhood_id: 24)
Attraction.create!(name: "The Brickyard Shopping Mall", address: "2600 N Narragansett Ave, Chicago, IL", neighborhood_id: 25)
Attraction.create!(name: "Ponce Restaurant", address: "4313 W Fullerton Ave, Chicago, IL", neighborhood_id: 26)
Attraction.create!(name: "Humboldt Park", address: "1400 N Humboldt Dr
Chicago, IL", neighborhood_id: 27)
Attraction.create!(name: "WHISK", address: "2018 W Chicago Ave, Chicago, IL", neighborhood_id: 28)
Attraction.create!(name: "Babas Famous Steak and Lemonade", address: "3958 W Monroe St, Chicago, IL", neighborhood_id: 30)
Attraction.create!(name: "Garfield Park Gold Dome Field House", address: "100 N Central Park Ave, Chicago, IL", neighborhood_id: 31)
Attraction.create!(name: "BomboBar West Loop", address: "832 W Randolph St, Chicago, IL", neighborhood_id: 32)
Attraction.create!(name: "Lagunitas Brewing Company", address: "2607 W 17th St, Chicago, IL", neighborhood_id: 33)
Attraction.create!(name: "La Catedral Cafe and Restaurant", address: "2500 S Christiana Ave, Chicago, IL", neighborhood_id: 34)
Attraction.create!(name: "Thalia Hall", address: "1807 S Allport St, Chicago, IL", neighborhood_id: 35)
Attraction.create!(name: "Burnham Park", address: "5491 S Shore Dr, Chicago, IL", neighborhood_id: 37)
Attraction.create!(name: "Oakwood - 41st Street Beach", address: "4100 S Lake Shore Dr, Chicago, IL", neighborhood_id: 38)
Attraction.create!(name: "Nicky's Gyros", address: "4240 S Wentworth Ave, Chicago, IL", neighborhood_id: 39)
Attraction.create!(name: "Ain't She Sweet Cafe", address: "2920, 526 E 43rd St, Chicago, IL", neighborhood_id: 40)
Attraction.create!(name: "George Blossom House - Frank Lloyd Wright", address: "4858 S Kenwood Ave, Chicago, IL", neighborhood_id: 41)
Attraction.create!(name: "Ms. Biscuit", address: "5431 S Wabash Ave, Chicago, IL", neighborhood_id: 42)
Attraction.create!(name: "Museum of Science and Industry", address: "5700 S Lake Shore Dr, Chicago, IL", neighborhood_id: 43)
Attraction.create!(name: "Jackson Park Golf Course", address: "6401 S Richards Dr, Chicago, IL", neighborhood_id: 44)
Attraction.create!(name: "KFC", address: "7445 S Stony Island Ave, Chicago, IL 60649", neighborhood_id: 45)
Attraction.create!(name: "Original Soul Vegetarian", address: "203 E 75th St, Chicago, IL", neighborhood_id: 47)
Attraction.create!(name: "Beggars Pizza", address: "5133 S Cicero Ave, Chicago, IL", neighborhood_id: 48)
Attraction.create!(name: "Paco's Tacos", address: "4311 S Archer Ave, Chicago, IL", neighborhood_id: 50)
Attraction.create!(name: "McKinley Park", address: "2210 W Pershing Rd, Chicago, IL", neighborhood_id: 51)
Attraction.create!(name: "Sherman Park", address: "1301 W 52nd St, Chicago, IL", neighborhood_id: 52)
Attraction.create!(name: "El Solazo", address: "5600 S Pulaski Rd, Chicago, IL", neighborhood_id: 53)
Attraction.create!(name: "Just One More Sports Bar", address: "5332 S Kedzie Ave, Chicago, IL", neighborhood_id: 54)
Attraction.create!(name: "Vince's Restaurant and Pizzeria", address: "6217 W 63rd St, Chicago, IL", neighborhood_id: 55)
Attraction.create!(name: "Balzekas Museum of Lithuanian Culture", address: "6500 S Pulaski Rd, Chicago, IL", neighborhood_id: 56)
Attraction.create!(name: "Marquette Park Golf Course", address: "6700 S Kedzie Ave, Chicago, IL", neighborhood_id: 57)
Attraction.create!(name: "Ogden Park", address: "6500 S Racine Ave, Chicago, IL", neighborhood_id: 58)
Attraction.create!(name: "Kennedy-King College", address: "6301 S Halsted St, Chicago, IL", neighborhood_id: 59)
Attraction.create!(name: "Dat Doughnut", address: "8251 S Cottage Grove Ave, Chicago, IL", neighborhood_id: 60)
Attraction.create!(name: "Rocky's Pancake House", address: "2948 E 83rd St, Chicago, IL", neighborhood_id: 62)
Attraction.create!(name: "Burnside Park", address: "9400 S Greenwood Ave, Chicago, IL", neighborhood_id: 63)
Attraction.create!(name: "The Logan Theater", address: "2646 N Milwaukee Ave, Chicago, IL", neighborhood_id: 8)
Attraction.create!(name: "Estereo", address: "2450 N Milwaukee Ave, Chicago, IL", neighborhood_id: 8)
Attraction.create!(name: "Margie's Candies", address: "1960 N Western Ave, Chicago, IL", neighborhood_id: 8)
Attraction.create!(name: "Emporium", address: "2363 N Milwaukee Ave, Chicago, IL", neighborhood_id: 8)
Attraction.create!(name: "Bronzeville Children's Museum", address: "9301 S Stony Island Ave, Chicago, IL", neighborhood_id: 64)
Attraction.create!(name: "Chicago State University", address: "9501 S King Dr, Chicago, IL", neighborhood_id: 65)
Attraction.create!(name: "National A. Philip Randolph Pullman Porter Museum", address: "10406 S Maryland Ave, Chicago, IL", neighborhood_id: 66)
Attraction.create!(name: "Harborside International Golf Center", address: "11001 South Doty Avenue East, Chicago, IL", neighborhood_id: 67)
Attraction.create!(name: "Calumet Park", address: "9801 S Ave G, Chicago, IL", neighborhood_id: 68)
Attraction.create!(name: "The Salvation Army Ray and Joan Kroc Corps Community Center Chicago", address: "1250 W 119th St, Chicago, IL", neighborhood_id: 69)
Attraction.create!(name: "Carver Park Pool", address: "939 E 132nd St, Chicago, IL", neighborhood_id: 70)
Attraction.create!(name: "William W. Powers State Recreation Area", address: "12949 S Avenue O, Chicago, IL", neighborhood_id: 71)
Attraction.create!(name: "Dan's Soul Food & Bakery", address: "2523 W 79th St, Chicago, IL", neighborhood_id: 72)
Attraction.create!(name: "Jamaican Jerk Villa", address: "737 W 79th St, Chicago, IL", neighborhood_id: 73)
Attraction.create!(name: "Top Notch Beefburgers", address: "2116 W 95th St, Chicago, IL", neighborhood_id: 74)
Attraction.create!(name: "Tony's Original Philly Steaks
", address: "1400 W 95th St, Chicago, IL", neighborhood_id: 75)
Attraction.create!(name: "Barraco's Pizza Chicago
", address: "3047 W 111th St, Chicago, IL", neighborhood_id: 76)
Attraction.create!(name: "Marshfield Plaza", address: "11730 Marshfield Ave, Chicago, IL", neighborhood_id: 77)

Vote.create!(user_id: 1, attraction_id: 3, value: true)
Vote.create!(user_id: 2, attraction_id: 3, value: false)
Vote.create!(user_id: 3, attraction_id: 3, value: false)
Vote.create!(user_id: 4, attraction_id: 3, value: false)
Vote.create!(user_id: 1, attraction_id: 1, value: true)
Vote.create!(user_id: 8, attraction_id: 3, value: true)
Vote.create!(user_id: 9, attraction_id: 3, value: false)
Vote.create!(user_id: 10, attraction_id: 3, value: true)
Vote.create!(user_id: 11, attraction_id: 3, value: false)
Vote.create!(user_id: 12, attraction_id: 1, value: true)
Vote.create!(user_id: 13, attraction_id: 1, value: false)
Vote.create!(user_id: 13, attraction_id: 3, value: true)

#Logan Theater id:68 neighborhood id == user_id: 8-11
Vote.create!(user_id: 1, attraction_id: 68, value: true)
Vote.create!(user_id: 2, attraction_id: 68, value: true)
Vote.create!(user_id: 3, attraction_id: 68, value: true)
Vote.create!(user_id: 4, attraction_id: 68, value: true)
Vote.create!(user_id: 5, attraction_id: 68, value: false)
Vote.create!(user_id: 6, attraction_id: 68, value: true)
Vote.create!(user_id: 7, attraction_id: 68, value: false)
Vote.create!(user_id: 8, attraction_id: 68, value: true)
Vote.create!(user_id: 9, attraction_id: 68, value: true)
Vote.create!(user_id: 10, attraction_id: 68, value: true)
Vote.create!(user_id: 11, attraction_id: 68, value: true)
Vote.create!(user_id: 12, attraction_id: 68, value: true)
Vote.create!(user_id: 13, attraction_id: 68, value: true)

#Estereo id:69
Vote.create!(user_id: 1, attraction_id: 69, value: true)
Vote.create!(user_id: 2, attraction_id: 69, value: true)
Vote.create!(user_id: 3, attraction_id: 69, value: true)
Vote.create!(user_id: 4, attraction_id: 69, value: true)
Vote.create!(user_id: 5, attraction_id: 69, value: true)
Vote.create!(user_id: 6, attraction_id: 69, value: true)
Vote.create!(user_id: 7, attraction_id: 69, value: true)
Vote.create!(user_id: 8, attraction_id: 69, value: true)
Vote.create!(user_id: 9, attraction_id: 69, value: false)
Vote.create!(user_id: 10, attraction_id: 69, value: false)
Vote.create!(user_id: 11, attraction_id: 69, value: false)
Vote.create!(user_id: 12, attraction_id: 69, value: true)
Vote.create!(user_id: 13, attraction_id: 69, value: true)

#Margie's Candies id:70
Vote.create!(user_id: 1, attraction_id: 70, value: true)
Vote.create!(user_id: 2, attraction_id: 70, value: true)
Vote.create!(user_id: 3, attraction_id: 70, value: true)
Vote.create!(user_id: 4, attraction_id: 70, value: true)
Vote.create!(user_id: 5, attraction_id: 70, value: true)
Vote.create!(user_id: 6, attraction_id: 70, value: true)
Vote.create!(user_id: 7, attraction_id: 70, value: true)
Vote.create!(user_id: 8, attraction_id: 70, value: true)
Vote.create!(user_id: 9, attraction_id: 70, value: true)
Vote.create!(user_id: 10, attraction_id: 70, value: true)
Vote.create!(user_id: 11, attraction_id: 70, value: true)
Vote.create!(user_id: 12, attraction_id: 70, value: true)
Vote.create!(user_id: 13, attraction_id: 70, value: true)

#Emporium id:71
Vote.create!(user_id: 1, attraction_id: 71, value: true)
Vote.create!(user_id: 2, attraction_id: 71, value: false)
Vote.create!(user_id: 3, attraction_id: 71, value: true)
Vote.create!(user_id: 4, attraction_id: 71, value: false)
Vote.create!(user_id: 5, attraction_id: 71, value: true)
Vote.create!(user_id: 6, attraction_id: 71, value: false)
Vote.create!(user_id: 7, attraction_id: 71, value: false)
Vote.create!(user_id: 8, attraction_id: 71, value: true)
Vote.create!(user_id: 9, attraction_id: 71, value: true)
Vote.create!(user_id: 10, attraction_id: 71, value: true)
Vote.create!(user_id: 11, attraction_id: 71, value: true)
Vote.create!(user_id: 12, attraction_id: 71, value: true)
Vote.create!(user_id: 13, attraction_id: 71, value: true)